name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-slim

    steps:
      - uses: dtolnay/rust-toolchain@stable
      - uses: paulusminus/rust-check@v5
        with:
          build: true
